### ISSUE TITLE
Add support for self-contained database

### ISSUE THREAD

**Issue by tobychui** [lunarr-app/lunarr-go#11]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have an old Windows PC running as my main server and I want to run this amazing project without MongoDB. Currently lunarr-go seems to be only supporting MongoDB as database.

**Describe the solution you'd like**
It would be nice if this project can integrate other self-contained database that do not require external database connections, like SQLite or KeyValue stores like BoltDB. If this is too much work for the project maintainer, a middleware for the database access will be great as well (so other contributors can add in their preferred database for this project). This can be done via designing an interface for the required database functions and use that middleware as abstraction to build other system functions.

**Additional context**
It can also be implemented as a fallback so when mongodb is not detected, the system won't panic but fallback to the build in self-contained db. 
![圖片](https://github.com/lunarr-app/lunarr-go/assets/24617523/da8e30c4-ebeb-4df8-8485-3ff2e5a75bcd)

**Comment by sayem314** [comment]
Your suggestion of integrating alternative self-contained databases like SQL* is valuable. It would provide users with more flexibility in choosing the database that best suits their needs.

Your feature request has been duly noted. Thank you for contributing your ideas to further improve this amazing project!

**Comment by sayem314** [comment]
**Update on Database Migration to Embedded SQL**

I have initiated the database migration process from MongoDB to an embedded SQL database solution. This migration aims to enhance the project's portability and eliminate the need for external database installation.

**Current Progress:**
- Research and Evaluation: I am actively researching and evaluating various embedded SQL database options.

**Next Steps:**
- Selection of Embedded SQL Database: Based on my research, I will carefully choose an embedded SQL database solution that aligns with our project requirements.
- Database Schema Design: Once the embedded SQL database is selected, I will work on designing the database schema to ensure compatibility with existing functionality and data.
- Code Modification: I will update the relevant code and dependencies to interact with the new embedded SQL database, enabling smooth data operations within our app.
- Testing and Validation: Thorough testing will be performed to validate the functionality and performance of the migrated database, ensuring a stable and reliable solution.

_Please stay tuned for further updates on the progress of the database migration. Your feedback and suggestions are always welcomed and greatly appreciated._

**Comment by sayem314** [comment]
**Update on Database Migration to Embedded SQL**

I have decided to proceed with GORM as the library for the embedded SQL database solution. This choice allows us to leverage the power of GORM's ORM capabilities while using a pure SQL embedded database.

Current Progress:

- I have integrated GORM into our project and established the necessary connections with the chosen embedded SQL database. And currently working on designing the database schema to align with our project requirements and ensure compatibility with existing functionality and data.

**Comment by darthShadow** [comment]
Have you considered using a type-safe library instead like [jet](https://github.com/go-jet/jet) or [sqlc](https://github.com/kyleconroy/sqlc).

In my experience, the compile time checks help a lot with any eventual refactoring or writing test cases and it's very helpful to know the exact SQL that's going to be used rather than being generated via the ORM.

**Comment by sayem314** [comment]
> Have you considered using a type-safe library instead like [jet](https://github.com/go-jet/jet) or [sqlc](https://github.com/kyleconroy/sqlc)?
> 
> In my experience, the compile time checks help a lot with any eventual refactoring or writing test cases and it's very helpful to know the exact SQL that's going to be used rather than being generated via the ORM.

Thank you for your suggestion. After considering various options, I have decided to proceed with GORM as the library for the embedded SQL database solution. GORM provides a balance between ORM convenience and the flexibility of working with a pure SQL embedded database. I appreciate your feedback and remain open to further discussions and suggestions.
